### PR TITLE
Support ipywidgets 8

### PR DESCRIPTION
**Pull request by jtpio**
Start testing support for `ipywidgets` 8.

Similar to https://github.com/matplotlib/ipympl/pull/461

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks!

Visual differences I'm ok with, do you know if the lab2 build can be fixed?

**Comment by jtpio** [comment]
Opened https://github.com/widgetti/ipyvolume/pull/412 to start troubleshooting this.

**Comment by maartenbreddels** [comment]
Ah, I think we need to manually push the visual changes right? Is there a bot that can do that for us?

**Comment by jtpio** [comment]
I opened https://github.com/widgetti/ipyvolume/issues/413 since this does not seem related to this change.

**Comment by jtpio** [comment]
Bringing this PR out of draft since `ipywidgets` 8 was released yesterday.

**Comment by maartenbreddels** [comment]
Failure needs network related. Thanks Jeremy!

**Pull request merged**
