### PR TITLE
MNT: Replace zmq ioloop with tornado

### PR DESCRIPTION
**Pull request by pllim**
Similar patch as https://github.com/glue-viz/glue-jupyter/pull/343

### CODE REVIEW

**Comment by pllim** [comment]
I don't think RTD failure is related?

**Comment by maartenbreddels** [comment]
> I don't think RTD failure is related?

No, I'll fix that separately.

**Comment by maartenbreddels** [comment]
ouch, some CI work to do I think!

**Comment by maartenbreddels** [comment]
Thank you!

**Comment by maartenbreddels** [comment]
This is released ipyvolume 0.6.0

**Comment by pllim** [comment]
Thank you!

**Pull request merged**
